### ISSUE TITLE
Internal Server Error When Authorizing Without Profile Picture

### ISSUE THREAD

**Issue by robiot** [dogehousetv/auth#15]
When you authorize with for example discord and you don't have a profile picture or it couldn't get some other data it gives this error:
`{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property 'substr' of undefined"}`

**Comment by lucemans** [comment]
https://github.com/dogehousetv/auth/blob/9e6661f4ad1403f9b5a7142857549b02a6827c50/src/controller/discord.ts#L47
